package com.via.himalaya.data.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.add
import kotlinx.serialization.json.buildJsonArray
import kotlinx.serialization.json.buildJsonObject
import kotlinx.serialization.json.put
import kotlinx.serialization.json.putJsonArray
import kotlinx.serialization.json.putJsonObject

/**
 * Points of interest for one trek, generated by scripts/process_treks.py and
 * served from R2 at trek_pois/<id>.json.
 */
@Serializable
data class TrekPoiBundle(
    @SerialName("trek_id")
    val trekId: String,
    @SerialName("trek_name")
    val trekName: String? = null,
    /** When the bundle was generated; mirrors treks.poi_updated_at. */
    @SerialName("generated_at")
    val generatedAt: String? = null,
    /** Which OSM snapshot the data came from. */
    @SerialName("osm_timestamp")
    val osmTimestamp: String? = null,
    val counts: Map<String, Int> = emptyMap(),
    val pois: List<TrekPoi> = emptyList()
)

@Serializable
data class TrekPoi(
    /** OSM identifier, e.g. "node/9117107250". */
    val id: String? = null,
    /** One of PoiCategory. */
    val category: String,
    /** Raw OSM value: ford, spring, camp_site, village... */
    val type: String,
    val name: String? = null,
    val lat: Double,
    val lon: Double,
    /** How far along the trail this sits, from the start. */
    @SerialName("dist_along_km")
    val distAlongKm: Double,
    /** Perpendicular distance from the trail - the cost of the detour. */
    @SerialName("offset_m")
    val offsetM: Int,
    /** "start" or "end" when the POI sits beyond a trail endpoint rather than alongside it. */
    @SerialName("off_route")
    val offRoute: String? = null,
    @SerialName("ele_m")
    val eleM: Double? = null,
    /** True when an OSM area was collapsed to its centroid, so the position is approximate. */
    @SerialName("approx_center")
    val approxCenter: Boolean = false,
    /** Higher = more likely to be occupied year-round. Bail-out targets only. */
    @SerialName("occupancy_rank")
    val occupancyRank: Int? = null,
    val tags: Map<String, String> = emptyMap()
) {
    /** True for things beside the trailhead rather than on the walk itself. */
    val isOnRoute: Boolean get() = offRoute == null
}

/**
 * The fixed set of categories the app renders. Which OSM tags feed each one is
 * decided in scripts/process_treks.py and can be re-mapped there at any time
 * without changing the app - only this list is contractual.
 */
object PoiCategory {
    const val WATER = "water"
    const val HOT_SPRING = "hot_spring"
    const val WATERFALL = "waterfall"
    const val LAKE = "lake"
    const val CAMP_SITE = "camp_site"
    const val STAY = "stay"
    const val SHELTER = "shelter"
    const val LANDMARK = "landmark"
    const val WATER_CROSSING = "water_crossing"

    /** Fallback for anything the backend fetched but could not map. */
    const val OTHER = "other"

    /** Draw order, back to front - a crossing must never hide under a guest house. */
    val DRAW_ORDER = listOf(
        OTHER, LANDMARK, SHELTER, STAY, CAMP_SITE,
        LAKE, WATERFALL, HOT_SPRING, WATER, WATER_CROSSING
    )

    /** Short label for the detail panel. */
    fun label(category: String): String = when (category) {
        WATER -> "Water"
        HOT_SPRING -> "Hot spring"
        WATERFALL -> "Waterfall"
        LAKE -> "Lake"
        CAMP_SITE -> "Camp site"
        STAY -> "Stay"
        SHELTER -> "Shelter"
        LANDMARK -> "Landmark"
        WATER_CROSSING -> "Water crossing"
        else -> "Other"
    }
}

/** "isolated_dwelling" -> "Isolated dwelling", and raw "key=value" left as-is for Other. */
fun TrekPoi.readableType(): String =
    if (type.contains('=')) type
    else type.replace('_', ' ').replaceFirstChar { it.uppercase() }

/**
 * Build a GeoJSON FeatureCollection for a Mapbox source.
 *
 * Properties are carried through so the layer can style or filter on them, and
 * so a tap can resolve back to the POI without a second lookup.
 */
fun List<TrekPoi>.toGeoJsonString(): String {
    val collection = buildJsonObject {
        put("type", "FeatureCollection")
        putJsonArray("features") {
            this@toGeoJsonString.forEach { poi ->
                add(
                    buildJsonObject {
                        put("type", "Feature")
                        putJsonObject("properties") {
                            put("id", poi.id)
                            put("category", poi.category)
                            put("type", poi.type)
                            put("name", poi.name)
                            put("dist_along_km", poi.distAlongKm)
                            put("offset_m", poi.offsetM)
                            put("on_route", poi.isOnRoute)
                            poi.eleM?.let { put("ele_m", it) }
                        }
                        putJsonObject("geometry") {
                            put("type", "Point")
                            putJsonArray("coordinates") {
                                add(JsonPrimitive(poi.lon))
                                add(JsonPrimitive(poi.lat))
                            }
                        }
                    }
                )
            }
        }
    }
    return collection.toString()
}
